### PR TITLE
fixing multiscale plotting

### PR DESCRIPTION
**Pull request by Artur-man**

### CODE REVIEW

**Comment by Artur-man** [comment]
There seems to be a solution from an old commit that solves this issue: 
https://github.com/HelenaLC/SpatialData/blob/cd74cc76d90f5a18dca17d76d3f5c2685e534eb0/R/plotting.R

`scale_y_reverse()` after each `annotation_raster` does the trick.

image

**Comment by Artur-man** [comment]
One problem is again with MERFISH that is that ... not just its scale but its extent is also different across points, shapes and images

```
dir.create(td <- tempfile())
pa <- unzip_merfish_demo(dest=td)
x <- readSpatialData(pa)

# plot image
g1 <- plotSpatialData() +
  plotImage(x)

# plot shape
g2 <- plotSpatialData() +
  plotShape(x, i="anatomical")

# plot point
i <- sample(length(p <- point(x)), 2e3)
point(x, "2k") <- p[i]
g3 <- plotSpatialData() +
  plotPoint(x, i="2k", c="cell_type", s=0.2)
```

image

**Comment by Artur-man** [comment]
Regarding the previous comment, the extent can be captured from the translation parameters: 

```
> x@images$rasterized@meta$multiscales$coordinateTransformations[[1]]$transformations[[1]]$translation
[[1]]
NULL

[[2]]
[1]    0 4548 1154
```

which we can use `coord2graph` function that @HelenaLC implemented.

**Comment by Artur-man** [comment]
Seems to be fixed with my local branch ... we can check, clean and push later!

image

**Comment by Artur-man** [comment]
Cropping looks to be working but the same cropping operations requires overwriting the translation parameters of .zattrs 

image

**Comment by HelenaLC** [comment]
Yes, im working on basic subsetting operations and these require setting translations - confirmed by Python ppl. Will pr when ready

**Comment by Artur-man** [comment]
Hmm .. are we working on the same thing ? because subsetting the image array shouldnt be related to cropping images in physical space ... you only have to get the relative scaling parameters across scales.

**Comment by Artur-man** [comment]
I will send a commit you take a look at that and tell me if your current work is similar

**Pull request merged**
