### PR TITLE
Table utility functions & vignette

### PR DESCRIPTION
**Pull request by LouiseDck**
Adds some utility functions
Based on [this notebook](https://github.com/scverse/spatialdata-notebooks/blob/main/notebooks/examples/tables.ipynb)

### CODE REVIEW

**Comment by HelenaLC** [comment]
one issue I just noticed is that `anndataR` seams to not read in `uns`, which contains the `spatialdata_attrs`? See code and screenshot ... am I missing something or would it be worth filing an issue with `anndataR`?
```
> x <- file.path("extdata", "blobs.zarr")
> x <- system.file(x, package="SpatialData")
> x <- file.path(x, "tables", "table")
> metadata(.readTable_anndataR(x))
list()
> metadata(.readTable_basilisk(x))
$spatialdata_attrs
$spatialdata_attrs$instance_key
[1] "instance_id"

$spatialdata_attrs$region
[1] "blobs_labels"

$spatialdata_attrs$region_key
[1] "region"
```
image

**Comment by LouiseDck** [comment]
Oh wow, you're right! I don't know how I missed this.
It's fixed now (in the "keller-mark/anndataR" repo in the "spatialdata" branch), but it probably means that the unit test in `test_methods.R` isn't working, I'll have a look at it soon.

**Comment by HelenaLC** [comment]
I think there was anyways a but that was dropping the `metadata` in both cases, thereby passing tests. I'll see if it's all in order now! FYI, I did a revision on `tables` handling following your draft (which really helped, because I had a hard time following initially) - there's examples in the README demo & I'll implement unit tests for these methods next. Then see how we can flexibly incorporate them into existing plotting functionality.

**Comment by HelenaLC** [comment]
All in order now:
```
> x <- file.path("extdata", "blobs.zarr")
> x <- system.file(x, package="SpatialData")
> x <- file.path(x, "tables", "table")
> metadata(.readTable_anndataR(x))
$spatialdata_attrs
$spatialdata_attrs$instance_key
[1] "instance_id"

$spatialdata_attrs$region
[1] "blobs_labels"

$spatialdata_attrs$region_key
[1] "region"


> metadata(.readTable_basilisk(x))
$spatialdata_attrs
$spatialdata_attrs$instance_key
[1] "instance_id"

$spatialdata_attrs$region
[1] "blobs_labels"

$spatialdata_attrs$region_key
[1] "region"
```

**Pull request merged**
